#pragma once

#define SPLIT_USB_DETECT


#define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"


#define LONG_TAPPING_TERM 220
#define TAPPING_TERM 180
#define MIDDLE_TAPPING_TERM 160
#define SHORT_TAPPING_TERM 120
#define TAP_DANCE_TAPPING_TERM 250

#define TAPPING_TOGGLE 3
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD

#define NO_ACTION_ONESHOT

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 50
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 8
#define MOUSEKEY_MAX_SPEED 48
#define MOUSEKEY_TIME_TO_MAX 16
#define MOUSEKEY_FRICTION 24
