#define TAPPING_TERM 180
#define MIDDLE_TAPPING_TERM 160
#define SHORT_TAPPING_TERM 110
#define TAPPING_TOGGLE 3
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
/* #define RETRO_TAPPING */
